name: feature-expo-tailwind

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  BASE_URL: https://raw.githubusercontent.com/t-i-f/feature-expo/main/tailwind

jobs:
  init-expo-tailwind:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cleanup
      run: |
        shopt -s extglob
        rm -rf !(.github)

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Use the version of Node.js you prefer

    - name: Install deps
      run: |
        npx expo install nativewind tailwindcss react-native-reanimated react-native-safe-area-context

    - name: Init tailwind
      run: |
        npx tailwindcss init

    - name: Customize Expo
      run: |
        npx expo customize metro.config.js
        npx expo customize babel.config.js

    - name: Downloads
      run: |
        npx @tisf/get -f "$BASE_URL/tailwind.config.js" .
        npx @tisf/get -f "$BASE_URL/metro.config.js" .
        npx @tisf/get -f "$BASE_URL/babel.config.js" .
        npx @tisf/get -f "$BASE_URL/nativewind-env.d.ts" .
        npx @tisf/get -f "$BASE_URL/global.css" .

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Set up Tailwind in Expo app with nativewind'

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true
